"""se arreglan los modelos de users

Revision ID: 0ab993e283d1
Revises: b7ac4eafd647
Create Date: 2025-10-14 19:45:47.961294

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "0ab993e283d1"
down_revision: str | Sequence[str] | None = "b7ac4eafd647"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
