"""se arreglan los modelos de users

Revision ID: 14c0adbfcad7
Revises: 0ab993e283d1
Create Date: 2025-10-14 19:46:05.504394

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "14c0adbfcad7"
down_revision: str | Sequence[str] | None = "0ab993e283d1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
