"""tabla recipes y tabla intermedia recipe-ingredients

Revision ID: 1b56329adfc0
Revises: b24286c2e192
Create Date: 2025-10-25 22:12:58.837919

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1b56329adfc0"
down_revision: str | Sequence[str] | None = "b24286c2e192"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recipes",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("instructions", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("prep_time", sa.Integer(), nullable=True),
        sa.Column("recipe_id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("servings", sa.Integer(), nullable=True),
        sa.Column(
            "visibility",
            sa.Enum("PUBLIC", "PRIVATE", name="recipevisibility"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("update_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("recipe_id"),
    )
    op.create_table(
        "recipe_ingredients",
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("optional", sa.Boolean(), nullable=False),
        sa.Column("recipe_ingredient_id", sa.Uuid(), nullable=False),
        sa.Column("recipe_id", sa.Uuid(), nullable=False),
        sa.Column("ingredient_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ingredient_id"],
            ["ingredients.ingredient_id"],
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.recipe_id"],
        ),
        sa.PrimaryKeyConstraint("recipe_ingredient_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("recipe_ingredients")
    op.drop_table("recipes")
    # ### end Alembic commands ###
