"""agrega tabla ingredients

Revision ID: 9ff77af7f43e
Revises: 14c0adbfcad7
Create Date: 2025-10-23 21:14:25.698082

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9ff77af7f43e"
down_revision: str | Sequence[str] | None = "14c0adbfcad7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingredients",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("default_unit", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("ingredient_id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("ingredient_id"),
        sa.UniqueConstraint("ingredient_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ingredients")
    # ### end Alembic commands ###
