"""reparo relacion de ingredientes-categorias

Revision ID: b24286c2e192
Revises: f9095d415380
Create Date: 2025-10-24 21:35:07.426204

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b24286c2e192"
down_revision: str | Sequence[str] | None = "f9095d415380"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Usamos batch_alter_table para compatibilidad con SQLite
    with op.batch_alter_table("ingredients", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_ingredients_category_id_categories",  # Nombre de la restricción
            "categories",  # Tabla referenciada
            ["category_id"],  # Columna local
            ["category_id"],  # Columna remota
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Usamos batch_alter_table para compatibilidad con SQLite
    with op.batch_alter_table("ingredients", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_ingredients_category_id_categories",  # Mismo nombre de restricción
            type_="foreignkey",
        )

    # ### end Alembic commands ###
